from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _iter_autogen_targets() -> list[Path]:
    targets = [
        ROOT / "game" / "data" / "art_manifest.json",
        ROOT / "game" / "data" / "bgm_manifest.json",
        ROOT / "game" / "data" / "audio_manifest.json",
        ROOT / "game" / "data" / "biome_manifest.json",
        ROOT / "game" / "data" / "prompt_manifest.json",
        ROOT / "game" / "data" / "art_manifest_cards.json",
        ROOT / "game" / "data" / "art_manifest_enemies.json",
        ROOT / "game" / "data" / "art_manifest_guides.json",
        ROOT / "game" / "data" / "art_manifest_avatar.json",
    ]
    for base in [ROOT / "assets", ROOT / "game" / "assets"]:
        targets.extend((base / "sprites" / "cards").glob("*.png"))
        targets.extend((base / "sprites" / "enemies").glob("*.png"))
        targets.extend((base / "music").glob("*.wav"))
        targets.extend((base / "music").glob("*.ogg"))
        targets.extend((base / "sfx").glob("generated*"))
    return targets


def _safe_delete(path: Path) -> tuple[bool, str]:
    try:
        if not path.exists():
            return False, "missing"
        if path.is_dir():
            # only remove generated-like dirs
            if "generated" in path.name.lower():
                for child in sorted(path.rglob("*"), reverse=True):
                    if child.is_file():
                        child.unlink(missing_ok=True)
                    elif child.is_dir():
                        child.rmdir()
                path.rmdir()
                return True, "dir_removed"
            return False, "skip_dir"
        path.unlink()
        return True, "removed"
    except PermissionError:
        return False, "locked (close game/audio and retry, or use --mark_only)"
    except Exception as exc:
        return False, f"error:{exc}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Safe cleanup for autogenerated artifacts.")
    parser.add_argument("--all", action="store_true", help="Delete known autogen outputs and generated assets.")
    parser.add_argument("--mark_only", action="store_true", help="Do not delete files; create .regen_flag marker.")
    args = parser.parse_args()

    if not args.all and not args.mark_only:
        print("[clean_autogen] choose one: --all or --mark_only")
        return 0

    flag = ROOT / ".regen_flag"

    if args.mark_only:
        try:
            flag.write_text("regen_requested=1\n", encoding="utf-8")
            print(f"[clean_autogen] mark_only OK -> {flag}")
        except Exception as exc:
            print(f"[clean_autogen] mark_only WARNING: {exc}")
        return 0

    removed = 0
    skipped = 0
    for path in _iter_autogen_targets():
        ok, msg = _safe_delete(path)
        if ok:
            removed += 1
            print(f"[clean_autogen] removed {path.relative_to(ROOT)}")
        else:
            skipped += 1
            if msg not in {"missing", "skip_dir"}:
                print(f"[clean_autogen] skip {path.relative_to(ROOT)} -> {msg}")

    try:
        flag.write_text("regen_requested=1\n", encoding="utf-8")
    except Exception:
        pass

    print(f"[clean_autogen] done removed={removed} skipped={skipped}")
    print("[clean_autogen] note: on Windows lock errors, close pygame/game process or use --mark_only.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
